apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: powerdns
resources:
  - powerdns-deploy.yml
  - powerdns-svc.yml
  - powerdns-ing.yml
  - powerdns-pvc.yml
  - powerdns-spc.yml
  - powerdns-sa.yml
  - powerdns-ns.yml
  - mariadb-deploy.yml
  - mariadb-svc.yml
  - powerdns-admin/
