---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: powerdns-mariadb
  annotations:
    nfs.io/storage-path: "data01/powerdns/db"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: powerdns-mariadb-admin
  annotations:
    nfs.io/storage-path: "data01/powerdns/db-admin"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
