---
apiVersion: v1
kind: Service
metadata:
  name: powerdns-admin
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: powerdns-admin
  selector:
    app: powerdns-admin
    part-of: powerdns
